sudo: false  # https://docs.travis-ci.com/user/ci-environment/
language: python
cache: pip
matrix:
  include:
    - python: 2.7
      env: FLASK=0.12
    - python: 2.7
      env: FLASK=1.0
    - python: 3.4
      env: FLASK=0.12
    - python: 3.4
      env: FLASK=1.0
    - python: 3.5
      env: FLASK=0.12
    - python: 3.5
      env: FLASK=1.0
    - python: 3.6
      env: FLASK=0.12
    - python: 3.6
      env: FLASK=1.0
    - python: 3.6
      env: FLASK=1.1
    - python: 3.7
      env: FLASK=0.12
    - python: 3.7
      env: FLASK=1.0
    - python: 3.7
      env: FLASK=1.1
    - python: pypy
      env: FLASK=0.12
    - python: pypy
      env: FLASK=1.0
    - python: pypy3
      env: FLASK=0.12
    - python: pypy3
      env: FLASK=1.0
    - python: pypy3
      env: FLASK=1.1

install:
  - pip install -q Flask==$FLASK
  - pip install coveralls
script: make ci
after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: change
